source: app
title: ElectionData
# To exclude inside docs/
exclude:
  - assets/scripts
  - assets/styles
  - assets/graphics/collecticons
baseurl: ".."
timezone: America/New_York
kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  guide/about:
    output: true

  guide/contributing:
    output: true

  guide/use:
    output: true